dhcp_conf_folder: '../inventories/services/'
dhcp_generated_cfg: '{{dhcp_conf_folder}}/dhcpd.conf'

demo:
  domain_name: demo.bootcamp.smpte
  default_lease_time: 600
  max_lease: 3600
  authoritative: true

  #TODO get ridof this
  clients:
      - {name: MuonEncapGateway, mac: '40:a3:6b:a0:3b:c8', ip4: 192.168.1.2}
      - {name: MuonDecapGateway, mac: '40:a3:6b:a0:29:dc', ip4: 192.168.1.3}

  subnets:
    control:
      - network: 192.168.1.0
        description: 'CTRL SUBNET (VLAN 3)'
        netmask: 255.255.255.0
        gateway: 192.168.1.254
        start: 192.168.1.10
        end:   192.168.1.100
