---

- name: Get information from NetBox
  get_netbox_data:
    nb_host: '{{ netbox_url }}'
    token: '{{ netbox_token }}'
    config_dir: '{{ config_dir }}'
    device_role: '{{ device_role }}'
    inventory_hostname: '{{ inventory_hostname }}'
  delegate_to: localhost
