---
all:
  children:
    DC:
      children:
        AVD_L2LEAFS:
          children:
            AVD_L2LEAF1:
              hosts:
                switch1:
                  ansible_host: 192.168.0.1
                  device_platform: 7280SR2-48YC6
                  type: l2leaf
  vars:
    config_dir: '../inventories/switch/intended/structured_configs/'
    device_role: 'standalone-media-switch'
    # Replace username and password for your deployment
    ansible_user: admin
    ansible_ssh_pass: admin
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    target_type: switch
