---
# tasks file for get_netbox_data
# - name: Get Prefixes and Connection information from NetBox
#   tags: [update]
#   get_netbox_data:
#     nb_host: '{{ netbox_url }}'
#     token: "{{vault_netbox_prod}}"
#     network: '{{system}}'
#     sub_networks: "{{ op_network }}"
#     locations: {'rt' : '{{ root_dir }}/{{ city }}/{{ system }}_rt' , 
#                 'ctrl' : '{{ root_dir }}/{{ city }}/{{ system }}_ctrl' ,
#                 'vars' : '{{ root_dir }}/{{ city }}/netbox_vars/{{ system }}' ,
#                 'cvp_name' : '{{ cvp_name }}' , 
#                 'cvp_ip' : '{{cvp_ip_address}}' }
#   delegate_to: localhost

- name: Get Prefixes and Connection information from NetBox using Graph QL
  get_netbox_graphql:
    nb_host: '{{ netbox_url }}'
    token: "{{ netbox_token }}"
  delegate_to: localhost
