network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eno1: # uplink
            dhcp4: true
            dhcp4-overrides:
                route-metric: 100
    enx00e04c0208a4:
            addresses:
              - 192.168.0.254/24
