---
- name: UPDATE DHCP CONFIG
  hosts:
    MuonDecapGateway
    MuonEncapGateway
  connection: local
  gather_facts: false
  vars_files:
    - ../inventories/services/dhcp.yml
  vars:
    - ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: Get Netbox Data
      tags: [netbox]
      import_role:
        name: netbox
    - name: 'Create DHCP Configs Directory'
      file: 'path={{ dhcp_conf_folder }}  state=directory'
      tags: generate
    - name: 'Generate DHCPd configuration file locally'
      template:
        src: '../templates/dhcpd.conf.j2'
        dest: '{{ dhcp_generated_cfg }}'
        mode: '0644'
      delegate_to: localhost
      tags: generate
