---
- name: Upload Config
  hosts: MTL-LAB1S3-MPX-XLF229
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: generate device intended config and documentation
      import_role:
        name: arista.avd.eos_cli_config_gen
    - name: provision switch with AVD configuration
      vars:
        eos_config_deploy_eapi_pre_running_config_backup: true
      import_role:
        name: arista.avd.eos_config_deploy_eapi
