---
all:
  children:
    DC:
      hosts:
        gateway1:
          device_role: 'ip-to-hdmi-gateway'
        gateway2:
          device_role: 'sdi-to-ip-gateway'
  vars:
    config_dir: '../inventories/gateways/intended/structured_configs/'
