---
all:
  children:
    DC:
      hosts:
        prout:
          ansible_host: 192.168.0.1
          device_role: 'ip-to-hdmi-gateway'
  vars:
    config_dir: '../inventories/gateways/intended/structured_configs/'
